LapTrinhWeb/LapTrinhWeb/Controllers/ExampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LapTrinhWeb.Controllers
{
    public class ExampleController : Controller
    {
        // GET: Example
        public ActionResult Index()
        {
            return View();
        }
    }
}

LapTrinhWeb/LapTrinhWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LapTrinhWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LapTrinhWeb/LapTrinhWeb/Controllers/QuanLyBaoCaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LapTrinhWeb.Controllers
{
    public class QuanLyBaoCaoController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MonthlyIntendedOrder()
        {
            ViewBag.Message = "something";
            return View();
        }

        public ActionResult BaoCaoDuTruThietBi()
        {
            ViewBag.Message = "bao cao du tru thiet bi";
            return View();
        }

        public ActionResult BaoCaoNhapMoiThietBi()
        {
            ViewBag.Message = "bao cao nhap moi thiet bi";
            return View();
        }

        public ActionResult BaoCaoDieuChuyenThietBi()
        {
            ViewBag.Message = "bao cao dieu chuyen thiet bi";
            return View();
        }
    }
}

LapTrinhWeb/LapTrinhWeb/Controllers/QuanLyHopDongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LapTrinhWeb.Controllers
{
    public class QuanLyHopDongController : Controller
    {
        // GET: ToolManage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult HopDongKhachHang()
        {
            return View();
        }

        public ActionResult HopDongNhaCungCap()
        {
            return View();
        }
    }
}

LapTrinhWeb/LapTrinhWeb/Controllers/QuanLyPhongBanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LapTrinhWeb.Controllers
{
    public class QuanLyPhongBanController : Controller
    {
        // GET: QuanLyPhongBan
        public ActionResult DanhSachPhongBan()
        {
            return View();
        }
    }
}

LapTrinhWeb/LapTrinhWeb/Controllers/QuanLyThietBiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LapTrinhWeb.Controllers
{
    public class QuanLyThietBiController : Controller
    {
        // GET: EquirementManager
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DanhSachXuatXu()
        {
            return View();
        }

        public ActionResult DanhSachHangSanXuat()
        {
            return View();
        }

        public ActionResult DanhSachLoaiThietBi()
        {
            return View();
        }

        public ActionResult DanhSachThietBi()
        {
            return View();
        }

    }
}

LapTrinhWeb/LapTrinhWeb/Views/Example/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>hello word</h2>
   

LapTrinhWeb/LapTrinhWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LapTrinhWeb/LapTrinhWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LapTrinhWeb/LapTrinhWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div>Home</div>

LapTrinhWeb/LapTrinhWeb/Views/Home/Report.cshtml
@{
    ViewBag.Title = "Report";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>

    </div>
</body>
</html>

LapTrinhWeb/LapTrinhWeb/Views/Order/MonthlyIntendedOrder.cshtml
@{
    ViewBag.Title = "MonthlyIntendedOrder";
}

<h1> Hello</h1>

LapTrinhWeb/LapTrinhWeb/Views/QuanLyBaoCao/BaoCaoDieuChuyenThietBi.cshtml
@{
    ViewBag.Title = "BaoCaoDieuChuyenThietBi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Báo cáo điều chuyển thiết bị</h1>

LapTrinhWeb/LapTrinhWeb/Views/QuanLyBaoCao/BaoCaoDuTruThietBi.cshtml
@{
    ViewBag.Title = "BaoCaoDuTruThietBi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Báo cáo dự trù thiết bị</h1>

LapTrinhWeb/LapTrinhWeb/Views/QuanLyBaoCao/BaoCaoNhapMoiThietBi.cshtml
@{
    ViewBag.Title = "BaoCaoNhapMoiThietBi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Báo cáo nhập mới thiết bị</h1>

LapTrinhWeb/LapTrinhWeb/Views/QuanLyBaoCao/MonthlyIntendedOrder.cshtml
@{
    ViewBag.Title = "MonthlyIntendedOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>hello</h1>

LapTrinhWeb/LapTrinhWeb/Views/QuanLyHopDong/HopDongKhachHang.cshtml
@{
    ViewBag.Title = "HopDongKhachHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>HopDongKhachHang</h2>

LapTrinhWeb/LapTrinhWeb/Views/QuanLyHopDong/HopDongNhaCungCap.cshtml
@{
    ViewBag.Title = "HopDongNhaCungCap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>HopDongNhaCungCap</h2>

LapTrinhWeb/LapTrinhWeb/Views/QuanLyPhongBan/DanhSachPhongBan.cshtml
@{
    ViewBag.Title = "DanhSachPhongBan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Danh mục phòng ban</h2>
<div class="container">
    <!-- Button to Open the Modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ThemPhongBan">
        Thêm mới
    </button>

    <!-- The Modal -->
    <div class="modal fade" id="ThemPhongBan">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Thêm mới phòng ban</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <form action="." method="post">
                        <div class="form-group">
                            <label>Mã đơn vị:</label>
                            <input class="form-control" placeholder="Thêm mã đơn vị">
                        </div>
                        <div class="form-group">
                            <label>Tên Đơn Vị:</label>
                            <input class="form-control" placeholder="Thêm tên đơn vị">
                        </div>
                        <div class="form-group">
                            <label>Địa chỉ:</label>
                            <input class="form-control" placeholder="Thêm địa chỉ">
                        </div>
                        <div class="form-group">
                            <label>Số điện thoại:</label>
                            <input class="form-control" placeholder="Thêm số điện thoại">
                        </div>
                        <div class="form-group">
                            <label>Tên ghi chú:</label>
                            <input class="form-control" placeholder="Thêm ghi chú">
                        </div>
                    </form>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy bỏ</button>
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            </div>
        </div>
    </div>

</div>
<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Mã đơn vị</th>
                <th>Tên đơn vị</th>
                <th>Địa chỉ</th>
                <th>Số điện thoại</th>
                <th>Ghi chú</th>
                <th>Sửa/Xóa</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#CapNhatPhongBan">Sửa</button>
                    <div class="modal fade" id="CapNhatPhongBan">
                        <div class="modal-dialog">
                            <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Thêm mới phòng ban</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <form action="." method="post">
                                        <div class="form-group">
                                            <label>Mã đơn vị:</label>
                                            <input class="form-control" placeholder="Thêm mã đơn vị">
                                        </div>
                                        <div class="form-group">
                                            <label>Tên Đơn Vị:</label>
                                            <input class="form-control" placeholder="Thêm tên đơn vị">
                                        </div>
                                        <div class="form-group">
                                            <label>Địa chỉ:</label>
                                            <input class="form-control" placeholder="Thêm địa chỉ">
                                        </div>
                                        <div class="form-group">
                                            <label>Số điện thoại:</label>
                                            <input class="form-control" placeholder="Thêm số điện thoại">
                                        </div>
                                        <div class="form-group">
                                            <label>Tên ghi chú:</label>
                                            <input class="form-control" placeholder="Thêm ghi chú">
                                        </div>
                                    </form>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy bỏ</button>
                                    <button type="submit" class="btn btn-primary">Lưu</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-danger">Xóa</button>
                </td>
            </tr>
            <tr>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#CapNhatPhongBan">Sửa</button>
                    <div class="modal fade" id="CapNhatPhongBan">
                        <div class="modal-dialog">
                            <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Thêm mới phòng ban</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <form action="." method="post">
                                        <div class="form-group">
                                            <label>Mã đơn vị:</label>
                                            <input class="form-control" placeholder="Thêm mã đơn vị">
                                        </div>
                                        <div class="form-group">
                                            <label>Tên Đơn Vị:</label>
                                            <input class="form-control" placeholder="Thêm tên đơn vị">
                                        </div>
                                        <div class="form-group">
                                            <label>Địa chỉ:</label>
                                            <input class="form-control" placeholder="Thêm địa chỉ">
                                        </div>
                                        <div class="form-group">
                                            <label>Số điện thoại:</label>
                                            <input class="form-control" placeholder="Thêm số điện thoại">
                                        </div>
                                        <div class="form-group">
                                            <label>Tên ghi chú:</label>
                                            <input class="form-control" placeholder="Thêm ghi chú">
                                        </div>
                                    </form>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy bỏ</button>
                                    <button type="submit" class="btn btn-primary">Lưu</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-danger">Xóa</button>
                </td>
            </tr>
            <tr>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#CapNhatPhongBan">Sửa</button>
                    <div class="modal fade" id="CapNhatPhongBan">
                        <div class="modal-dialog">
                            <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Thêm mới phòng ban</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <form action="." method="post">
                                        <div class="form-group">
                                            <label>Mã đơn vị:</label>
                                            <input class="form-control" placeholder="Thêm mã đơn vị">
                                        </div>
                                        <div class="form-group">
                                            <label>Tên Đơn Vị:</label>
                                            <input class="form-control" placeholder="Thêm tên đơn vị">
                                        </div>
                                        <div class="form-group">
                                            <label>Địa chỉ:</label>
                                            <input class="form-control" placeholder="Thêm địa chỉ">
                                        </div>
                                        <div class="form-group">
                                            <label>Số điện thoại:</label>
                                            <input class="form-control" placeholder="Thêm số điện thoại">
                                        </div>
                                        <div class="form-group">
                                            <label>Tên ghi chú:</label>
                                            <input class="form-control" placeholder="Thêm ghi chú">
                                        </div>
                                    </form>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy bỏ</button>
                                    <button type="submit" class="btn btn-primary">Lưu</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-danger">Xóa</button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

LapTrinhWeb/LapTrinhWeb/Views/QuanLyThietBi/DanhSachHangSanXuat.cshtml
@{
    ViewBag.Title = "DanhSachHangSanXuat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Danh mục hãng sản xuất</h2>
    <div class="container">
        <!-- Button to Open the Modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ThemHangSanXuat">
            Thêm mới
        </button>

        <!-- The Modal -->
        <div class="modal fade" id="ThemHangSanXuat">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Thêm mới hãng sản xuất</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        <form action="." method="post">
                            <div class="form-group">
                                <label> Xuất xứ:</label>
                                <input class="form-control" placeholder="Thêm tên hãng sản xuất">
                            </div>
                            <div class="form-group">
                                <label> Ghi chú:</label>
                                <input class="form-control" placeholder="Thêm ghi chú">
                            </div>
                        </form>
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy bỏ</button>
                        <button type="submit" class="btn btn-primary">Lưu</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Hãng sản xuất</th>
                <th>Ghi chú</th>
                <th>Sửa/Xóa</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>John</td>
                <td>Doe</td>
                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#CapNhatHangSanXuat">Sửa</button>
                    <div class="modal fade" id="CapNhatHangSanXuat">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Sửa thông tin hãng sản xuất</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <form action="." method="post">
                                        <div class="form-group">
                                            <label> Hãng sản xuất:</label>
                                            <input class="form-control" placeholder="Thêm tên hãng sản xuất">
                                        </div>
                                        <div class="form-group">
                                            <label> Ghi chú:</label>
                                            <input class="form-control" placeholder="Thêm ghi chú">
                                        </div>
                                    </form>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy</button>
                                    <button type="submit" class="btn btn-primary">Lưu</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-danger">Xóa</button>
                </td>
            </tr>
            <tr>
                <td>Mary</td>
                <td>Moe</td>
                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#CapNhattHangSanXuat">Sửa</button>
                    <div class="modal fade" id="CapNhatHangSanXuat">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Sửa thông tin hãng sản xuất</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <form action="." method="post">
                                        <div class="form-group">
                                            <label> Hãng sản xuất:</label>
                                            <input class="form-control" placeholder="Thêm tên hãng sản xuất">
                                        </div>
                                        <div class="form-group">
                                            <label> Ghi chú:</label>
                                            <input class="form-control" placeholder="Thêm ghi chú">
                                        </div>
                                    </form>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy</button>
                                    <button type="submit" class="btn btn-primary">Lưu</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-danger">Xóa</button>
                </td>
            </tr>
            <tr>
                <td>July</td>
                <td>Dooley</td>
                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#CapNhaHangSanXuat">Sửa</button>
                    <div class="modal fade" id="CapNhatHangSanXuat">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Sửa thông tin hãng sản xuất</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <form action="." method="post">
                                        <div class="form-group">
                                            <label> Hãng sản xuất:</label>
                                            <input class="form-control" placeholder="Thêm tên hãng sản xuất">
                                        </div>
                                        <div class="form-group">
                                            <label> Ghi chú:</label>
                                            <input class="form-control" placeholder="Thêm ghi chú">
                                        </div>
                                    </form>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy</button>
                                    <button type="submit" class="btn btn-primary">Lưu</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-danger">Xóa</button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

LapTrinhWeb/LapTrinhWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("X-Team", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>
                        <button class="btn btn-link dropdown-toggle" type="button" data-toggle="dropdown">
                            Danh mục quản lý
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Thiết Bị", "DanhSachThietBi", "QuanLyThietBi")</li>
                            <li>@Html.ActionLink("Phòng Ban", "DanhSachPhongBan", "QuanLyPhongBan")</li>
                        </ul>
                    </li>
                    <li>
                        <button class="btn btn-link dropdown-toggle" type="button" data-toggle="dropdown">
                            Báo cáo
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Dự trù thiết bị", "BaoCaoDuTruThietBi", "QuanLyBaoCao")</li>
                            <li>@Html.ActionLink("Nhập mới thiết bị", "BaoCaoNhapMoiThietBi", "QuanLyBaoCao")</li>
                            <li>@Html.ActionLink("Điều chuyển thiết bị", "BaoCaoDieuChuyenThietBi", "QuanLyBaoCao")</li>
                            <li>@Html.ActionLink("Du tru hang thang", "MonthlyIntendedOrder", "QuanLyBaoCao")</li>
                        </ul>
                    </li>
                    <li>
                        <button class="btn btn-link dropdown-toggle" type="button" data-toggle="dropdown">
                            Hợp đồng
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Hợp đồng khách hàng", "HopDongKhachHang", "QuanLyHopDong")</li>
                            <li>@Html.ActionLink("Hợp đồng nhà cung cấp", "HopDongNhaCungCap", "QuanLyHopDong")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>